name: bizzuser
description: "A production-ready Flutter application with GetX architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  image_picker: ^1.2.3
  razorpay_flutter: ^1.4.0
  google_maps_flutter: ^2.18.1
  socket_io_client: ^3.1.2
  geolocator: ^14.0.3
  share_plus: ^13.3.0
  url_launcher: ^6.3.2
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # Add font files under assets/fonts and uncomment below.
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
